# Generated by Django 6.0.6 on 2026-06-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
