# Generated by Django 6.0.6 on 2026-06-11 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_emp_email_employee_emp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
