# Generated by Django 6.0.6 on 2026-06-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_employee_of_month',
            field=models.BooleanField(default=False),
        ),
    ]
