# Generated by Django 6.0.6 on 2026-06-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_is_employee_of_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_head', models.CharField(blank=True, default='', max_length=50)),
                ('dept_description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
